### ISSUE TITLE
Feature request: store the information "this class is abstract"

### ISSUE THREAD

**Issue by yrodiere** [buschmais/jqa-java-plugin#15]
As far as I can see, the information is not currently extracted by this plugin.

In the Neo4j store, the information could be stored as a label (`:Abstract`) or simply as a property (`node.abstract = true`).

The information could be useful to relax some constraints ("each type must implement this method" may not make sense for abstract types), or to add constraints that are specific to abstract types ("Abstract types must have an 'Abstract' prefix in their name").

While we're at it, the information may be interesting for methods, too.

**Comment by DirkMahler** [comment]
There is already a property on type and method level, indicating that the element is abstract, see http://buschmais.github.io/jqassistant/doc/1.5.0/#:Java:Type. Just noticed that the documentation Method nodes does not describe the property, will be added.

**Comment by yrodiere** [comment]
Right... Apparently the property is not shown in the Neo4j explorer for non-abstract types, so I didn't see it.
Thank you for your quick answer, and sorry about the noise.

**Comment by DirkMahler** [comment]
It's hasn't been noise, the docs were incomplete.
