### ISSUE TITLE
Interface extension produces a ":IMPLEMENTS" releationship

### ISSUE THREAD

**Issue by jdufner** [buschmais/jqa-java-plugin#17]
Assume an interface like that: `interface SubInterface extends SuperInterface { ... }`

This results in jQA to an ":IMPLEMENTS" relationship. From my point of view it should create an ":EXTENDS" relationship.

Could you verify this?

**Comment by DirkMahler** [comment]
There's a "mismatch" of the representation in the Java source code using "extends" and the scanned bytecode which actually reports an "implements" relation so the representation is by intention. This breaks a bit the expectation of a Java developer but usually is not a problem as the most common use case checking assignability of types using both relation types, e.g. "(t1)-[:EXTENDS|IMPLEMENTS*]->(t2)".

**Comment by jdufner** [comment]
Thanks for clarification. In the [documentation](http://buschmais.github.io/jqassistant/doc/1.6.0/#:Java:Type) it is already mentioned, but I haven't read it before, sorry.

> Inheritance between interfaces (i.e. public interface A extends B { …​ }) is represented using IMPLEMENTS relations, i.e. queries must use (a:Type:Interface)-[:IMPLEMENTS]→(b:Type:Interface) for pattern matching.

But from my point of view a concept can help to meet developers experience. A cypher query to create an :EXTENDS relationship could be:

````
MATCH path=(sub:Java:Interface)-[:IMPLEMENTS]->(super:Java:Interface) MERGE (sub)-[:EXTENDS]->(super) RETURN COUNT(path) AS numberOfRelationships
````

**Comment by DirkMahler** [comment]
This would be a good candidate for an FAQ document that had already been asked for several times.
